spring:
  application:
    name: spring-doc-sample
server:
  port: 8080

# 日志配置
logging:
  level:
    com.zzq: debug

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  # 分组配置
  group-configs:
    - group: "index"
      paths-to-match: "/api/index/**"
    - group: "user"
      paths-to-match: "/api/user/**"




